sudo: false
language: node_js
node_js: 
 - "8"
 - "10"
 - "12"
dist: trusty
install:
 - npm ci
script:
  - npm run build
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  skip_cleanup: true